spring.application.name=justbinary

spring.datasource.url=jdbc:mysql://localhost:3306/justbinary
spring.datasource.username=root
spring.datasource.password=Joyot5417@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=justbinarySecretKey123456789012345
jwt.expiration=86400000

server.port=8080

mpesa.consumerKey=3OMVcMAYNXGXKo4MS8r7TnylAnzFmERTdTvvcG0Sf4PjiELl
mpesa.consumerSecret=GrpZKfGGeGW1kA7D23xH1vkhNtvMMvRAFGE1wbog8NzH7nJsuv87dOAHGWDGe1W3
mpesa.baseUrl=https://sandbox.safaricom.co.ke
mpesa.shortcode=174379
mpesa.passkey=Joyot5417
mpesa.callbackUrl=https://yourdomain.com/api/mpesa/callback
mpesa.b2cShortcode=600000
mpesa.b2cInitiatorName=testapi
mpesa.b2cSecurityCredential=your_credential
mpesa.b2cResultUrl=https://yourdomain.com/api/mpesa/callback
mpesa.b2cQueueUrl=https://yourdomain.com/api/mpesa/callback